import nock from 'nock'

import { DEFAULT_BASE_URL } from '../../src/config'

export const mockScheduleSuccessMalformed1 = (urlPath: string): nock.Scope =>
  nock(DEFAULT_BASE_URL, {
    encodedQueryParams: true,
  })
    .get(`/${urlPath}/scores/json/GamesByDate/2022-04-22`)
    .query({
      key: process.env.MLB_API_KEY,
    })
    .reply(200, () => ({ games: ['game1'] }), [
      'Content-Type',
      'application/json',
      'Connection',
      'close',
      'Vary',
      'Accept-Encoding',
      'Vary',
      'Origin',
    ])

export const mockScheduleSuccessNoEvents = (urlPath: string): nock.Scope =>
  nock(DEFAULT_BASE_URL, {
    encodedQueryParams: true,
  })
    .get(`/${urlPath}/scores/json/GamesByDate/2022-04-22`)
    .query({
      key: process.env.MLB_API_KEY,
    })
    .reply(200, () => [], [
      'Content-Type',
      'application/json',
      'Connection',
      'close',
      'Vary',
      'Accept-Encoding',
      'Vary',
      'Origin',
    ])

// 3 events, the one in the middle is skipped from market create (status !== 'Scheduled')
export const mockScheduleSuccessCreateMLB1 = (): nock.Scope =>
  nock(DEFAULT_BASE_URL, {
    encodedQueryParams: true,
  })
    .get(`/mlb/scores/json/GamesByDate/2022-04-24`)
    .query({
      key: process.env.MLB_API_KEY,
    })
    .reply(
      200,
      () => [
        {
          GameID: 64571,
          Season: 2022,
          SeasonType: 1,
          Status: 'Scheduled',
          Day: '2022-04-24T00:00:00',
          DateTime: '2022-04-24T13:10:00',
          AwayTeam: 'COL',
          HomeTeam: 'DET',
          AwayTeamID: 23,
          HomeTeamID: 17,
          RescheduledGameID: null,
          StadiumID: 62,
          Channel: 'ATRM,BSDT',
          Inning: null,
          InningHalf: null,
          AwayTeamRuns: null,
          HomeTeamRuns: null,
          AwayTeamHits: null,
          HomeTeamHits: null,
          AwayTeamErrors: null,
          HomeTeamErrors: null,
          WinningPitcherID: null,
          LosingPitcherID: null,
          SavingPitcherID: null,
          Attendance: null,
          AwayTeamProbablePitcherID: 10006172,
          HomeTeamProbablePitcherID: 10010609,
          Outs: null,
          Balls: null,
          Strikes: null,
          CurrentPitcherID: null,
          CurrentHitterID: null,
          AwayTeamStartingPitcherID: null,
          HomeTeamStartingPitcherID: null,
          CurrentPitchingTeamID: null,
          CurrentHittingTeamID: null,
          PointSpread: null,
          OverUnder: 8.5,
          AwayTeamMoneyLine: 110,
          HomeTeamMoneyLine: -125,
          ForecastTempLow: 77,
          ForecastTempHigh: 77,
          ForecastDescription: 'Broken Clouds',
          ForecastWindChill: 77,
          ForecastWindSpeed: 17,
          ForecastWindDirection: 213,
          RescheduledFromGameID: null,
          RunnerOnFirst: null,
          RunnerOnSecond: null,
          RunnerOnThird: null,
          AwayTeamStartingPitcher: 'Chad Kuhl',
          HomeTeamStartingPitcher: 'Tyler Alexander',
          CurrentPitcher: null,
          CurrentHitter: null,
          WinningPitcher: null,
          LosingPitcher: null,
          SavingPitcher: null,
          DueUpHitterID1: null,
          DueUpHitterID2: null,
          DueUpHitterID3: null,
          GlobalGameID: 10064571,
          GlobalAwayTeamID: 10000023,
          GlobalHomeTeamID: 10000017,
          PointSpreadAwayTeamMoneyLine: null,
          PointSpreadHomeTeamMoneyLine: null,
          LastPlay: null,
          IsClosed: false,
          Updated: '2022-04-23T15:33:27',
          GameEndDateTime: null,
          HomeRotationNumber: 930,
          AwayRotationNumber: 929,
          NeutralVenue: false,
          InningDescription: null,
          OverPayout: -110,
          UnderPayout: -110,
          DateTimeUTC: '2022-04-24T17:10:00',
          SeriesInfo: null,
          Innings: [],
        },
        {
          GameID: 64569,
          Season: 2022,
          SeasonType: 1,
          Status: 'Final',
          Day: '2022-04-24T00:00:00',
          DateTime: '2022-04-24T13:10:00',
          AwayTeam: 'BOS',
          HomeTeam: 'TB',
          AwayTeamID: 25,
          HomeTeamID: 11,
          RescheduledGameID: null,
          StadiumID: 18,
          Channel: 'MLBN,SUN,NESN',
          Inning: null,
          InningHalf: null,
          AwayTeamRuns: null,
          HomeTeamRuns: null,
          AwayTeamHits: null,
          HomeTeamHits: null,
          AwayTeamErrors: null,
          HomeTeamErrors: null,
          WinningPitcherID: null,
          LosingPitcherID: null,
          SavingPitcherID: null,
          Attendance: null,
          AwayTeamProbablePitcherID: 10000839,
          HomeTeamProbablePitcherID: 10009346,
          Outs: null,
          Balls: null,
          Strikes: null,
          CurrentPitcherID: null,
          CurrentHitterID: null,
          AwayTeamStartingPitcherID: null,
          HomeTeamStartingPitcherID: null,
          CurrentPitchingTeamID: null,
          CurrentHittingTeamID: null,
          PointSpread: null,
          OverUnder: 7.5,
          AwayTeamMoneyLine: 140,
          HomeTeamMoneyLine: -160,
          ForecastTempLow: 81,
          ForecastTempHigh: 81,
          ForecastDescription: 'Clear Sky',
          ForecastWindChill: 81,
          ForecastWindSpeed: 7,
          ForecastWindDirection: 88,
          RescheduledFromGameID: null,
          RunnerOnFirst: null,
          RunnerOnSecond: null,
          RunnerOnThird: null,
          AwayTeamStartingPitcher: 'Rich Hill',
          HomeTeamStartingPitcher: 'Shane McClanahan',
          CurrentPitcher: null,
          CurrentHitter: null,
          WinningPitcher: null,
          LosingPitcher: null,
          SavingPitcher: null,
          DueUpHitterID1: null,
          DueUpHitterID2: null,
          DueUpHitterID3: null,
          GlobalGameID: 10064569,
          GlobalAwayTeamID: 10000025,
          GlobalHomeTeamID: 10000011,
          PointSpreadAwayTeamMoneyLine: null,
          PointSpreadHomeTeamMoneyLine: null,
          LastPlay: null,
          IsClosed: false,
          Updated: '2022-04-23T15:27:26',
          GameEndDateTime: null,
          HomeRotationNumber: 916,
          AwayRotationNumber: 915,
          NeutralVenue: false,
          InningDescription: null,
          OverPayout: -115,
          UnderPayout: -105,
          DateTimeUTC: '2022-04-24T17:10:00',
          SeriesInfo: null,
          Innings: [],
        },
        {
          GameID: 64574,
          Season: 2022,
          SeasonType: 1,
          Status: 'Scheduled',
          Day: '2022-04-24T00:00:00',
          DateTime: '2022-04-24T13:35:00',
          AwayTeam: 'MIA',
          HomeTeam: 'ATL',
          AwayTeamID: 22,
          HomeTeamID: 26,
          RescheduledGameID: null,
          StadiumID: 68,
          Channel: 'BSSE,BSFL',
          Inning: null,
          InningHalf: null,
          AwayTeamRuns: null,
          HomeTeamRuns: null,
          AwayTeamHits: null,
          HomeTeamHits: null,
          AwayTeamErrors: null,
          HomeTeamErrors: null,
          WinningPitcherID: null,
          LosingPitcherID: null,
          SavingPitcherID: null,
          Attendance: null,
          AwayTeamProbablePitcherID: 10007082,
          HomeTeamProbablePitcherID: 10011485,
          Outs: null,
          Balls: null,
          Strikes: null,
          CurrentPitcherID: null,
          CurrentHitterID: null,
          AwayTeamStartingPitcherID: null,
          HomeTeamStartingPitcherID: null,
          CurrentPitchingTeamID: null,
          CurrentHittingTeamID: null,
          PointSpread: null,
          OverUnder: 8.0,
          AwayTeamMoneyLine: 130,
          HomeTeamMoneyLine: -150,
          ForecastTempLow: 81,
          ForecastTempHigh: 81,
          ForecastDescription: 'Broken Clouds',
          ForecastWindChill: 81,
          ForecastWindSpeed: 7,
          ForecastWindDirection: 158,
          RescheduledFromGameID: null,
          RunnerOnFirst: null,
          RunnerOnSecond: null,
          RunnerOnThird: null,
          AwayTeamStartingPitcher: 'Jesús Luzardo',
          HomeTeamStartingPitcher: 'Bryce Elder',
          CurrentPitcher: null,
          CurrentHitter: null,
          WinningPitcher: null,
          LosingPitcher: null,
          SavingPitcher: null,
          DueUpHitterID1: null,
          DueUpHitterID2: null,
          DueUpHitterID3: null,
          GlobalGameID: 10064574,
          GlobalAwayTeamID: 10000022,
          GlobalHomeTeamID: 10000026,
          PointSpreadAwayTeamMoneyLine: null,
          PointSpreadHomeTeamMoneyLine: null,
          LastPlay: null,
          IsClosed: false,
          Updated: '2022-04-23T15:25:13',
          GameEndDateTime: null,
          HomeRotationNumber: 904,
          AwayRotationNumber: 903,
          NeutralVenue: false,
          InningDescription: null,
          OverPayout: -125,
          UnderPayout: 105,
          DateTimeUTC: '2022-04-24T17:35:00',
          SeriesInfo: null,
          Innings: [],
        },
      ],
      [
        'Content-Type',
        'application/json',
        'Connection',
        'close',
        'Vary',
        'Accept-Encoding',
        'Vary',
        'Origin',
      ],
    )

// 3 events, the one in the middle is skipped from market resolve (status === 'Scheduled')
export const mockScheduleSuccessResolveMLB1 = (): nock.Scope =>
  nock(DEFAULT_BASE_URL, {
    encodedQueryParams: true,
  })
    .get('/mlb/scores/json/GamesByDate/2022-04-22')
    .query({
      key: process.env.MLB_API_KEY,
    })
    .reply(
      200,
      () => [
        {
          GameID: 64548,
          Season: 2022,
          SeasonType: 1,
          Status: 'Final',
          Day: '2022-04-22T00:00:00',
          DateTime: '2022-04-22T18:40:00',
          AwayTeam: 'STL',
          HomeTeam: 'CIN',
          AwayTeamID: 31,
          HomeTeamID: 2,
          RescheduledGameID: null,
          StadiumID: 64,
          Channel: 'APLTV',
          Inning: 9,
          InningHalf: 'B',
          AwayTeamRuns: 4,
          HomeTeamRuns: 2,
          AwayTeamHits: 10,
          HomeTeamHits: 9,
          AwayTeamErrors: 0,
          HomeTeamErrors: 1,
          WinningPitcherID: 10003259,
          LosingPitcherID: 10008354,
          SavingPitcherID: 10007380,
          Attendance: null,
          AwayTeamProbablePitcherID: 10003259,
          HomeTeamProbablePitcherID: 10008354,
          Outs: null,
          Balls: null,
          Strikes: null,
          CurrentPitcherID: null,
          CurrentHitterID: null,
          AwayTeamStartingPitcherID: 10003259,
          HomeTeamStartingPitcherID: 10008354,
          CurrentPitchingTeamID: null,
          CurrentHittingTeamID: null,
          PointSpread: 1.5,
          OverUnder: 8.0,
          AwayTeamMoneyLine: -130,
          HomeTeamMoneyLine: 110,
          ForecastTempLow: 61,
          ForecastTempHigh: 64,
          ForecastDescription: 'Clear Sky',
          ForecastWindChill: 64,
          ForecastWindSpeed: 5,
          ForecastWindDirection: 147,
          RescheduledFromGameID: null,
          RunnerOnFirst: null,
          RunnerOnSecond: null,
          RunnerOnThird: null,
          AwayTeamStartingPitcher: 'Steven Matz',
          HomeTeamStartingPitcher: 'Hunter Greene',
          CurrentPitcher: null,
          CurrentHitter: null,
          WinningPitcher: 'Steven Matz',
          LosingPitcher: 'Hunter Greene',
          SavingPitcher: 'Giovanny Gallegos',
          DueUpHitterID1: null,
          DueUpHitterID2: null,
          DueUpHitterID3: null,
          GlobalGameID: 10064548,
          GlobalAwayTeamID: 10000031,
          GlobalHomeTeamID: 10000002,
          PointSpreadAwayTeamMoneyLine: 130,
          PointSpreadHomeTeamMoneyLine: -160,
          LastPlay: null,
          IsClosed: true,
          Updated: '2022-04-22T22:34:36',
          GameEndDateTime: '2022-04-22T22:04:45',
          HomeRotationNumber: 904,
          AwayRotationNumber: 903,
          NeutralVenue: false,
          InningDescription: null,
          OverPayout: -106,
          UnderPayout: -115,
          DateTimeUTC: '2022-04-22T22:40:00',
          SeriesInfo: null,
          Innings: [
            {
              InningID: 416374,
              GameID: 64548,
              InningNumber: 1,
              AwayTeamRuns: 1,
              HomeTeamRuns: 0,
            },
            {
              InningID: 416379,
              GameID: 64548,
              InningNumber: 2,
              AwayTeamRuns: 0,
              HomeTeamRuns: 0,
            },
            {
              InningID: 416381,
              GameID: 64548,
              InningNumber: 3,
              AwayTeamRuns: 0,
              HomeTeamRuns: 0,
            },
            {
              InningID: 416387,
              GameID: 64548,
              InningNumber: 4,
              AwayTeamRuns: 2,
              HomeTeamRuns: 0,
            },
            {
              InningID: 416392,
              GameID: 64548,
              InningNumber: 5,
              AwayTeamRuns: 1,
              HomeTeamRuns: 1,
            },
            {
              InningID: 416406,
              GameID: 64548,
              InningNumber: 6,
              AwayTeamRuns: 0,
              HomeTeamRuns: 0,
            },
            {
              InningID: 416414,
              GameID: 64548,
              InningNumber: 7,
              AwayTeamRuns: 0,
              HomeTeamRuns: 0,
            },
            {
              InningID: 416423,
              GameID: 64548,
              InningNumber: 8,
              AwayTeamRuns: 0,
              HomeTeamRuns: 0,
            },
            {
              InningID: 416433,
              GameID: 64548,
              InningNumber: 9,
              AwayTeamRuns: 0,
              HomeTeamRuns: 1,
            },
          ],
        },
        {
          GameID: 64540,
          Season: 2022,
          SeasonType: 1,
          Status: 'Scheduled',
          Day: '2022-04-22T00:00:00',
          DateTime: '2022-04-22T19:05:00',
          AwayTeam: 'CLE',
          HomeTeam: 'NYY',
          AwayTeamID: 10,
          HomeTeamID: 29,
          RescheduledGameID: null,
          StadiumID: 35,
          Channel: null,
          Inning: 9,
          InningHalf: 'T',
          AwayTeamRuns: 1,
          HomeTeamRuns: 4,
          AwayTeamHits: 9,
          HomeTeamHits: 7,
          AwayTeamErrors: 0,
          HomeTeamErrors: 0,
          WinningPitcherID: 10007106,
          LosingPitcherID: 10009248,
          SavingPitcherID: 10000278,
          Attendance: null,
          AwayTeamProbablePitcherID: 10009248,
          HomeTeamProbablePitcherID: 10000986,
          Outs: null,
          Balls: null,
          Strikes: null,
          CurrentPitcherID: null,
          CurrentHitterID: null,
          AwayTeamStartingPitcherID: 10009248,
          HomeTeamStartingPitcherID: 10000986,
          CurrentPitchingTeamID: null,
          CurrentHittingTeamID: null,
          PointSpread: -1.5,
          OverUnder: 8.0,
          AwayTeamMoneyLine: 149,
          HomeTeamMoneyLine: -175,
          ForecastTempLow: 55,
          ForecastTempHigh: 57,
          ForecastDescription: 'Clear Sky',
          ForecastWindChill: 57,
          ForecastWindSpeed: 8,
          ForecastWindDirection: 12,
          RescheduledFromGameID: null,
          RunnerOnFirst: null,
          RunnerOnSecond: null,
          RunnerOnThird: null,
          AwayTeamStartingPitcher: 'Eli Morgan',
          HomeTeamStartingPitcher: 'Jameson Taillon',
          CurrentPitcher: null,
          CurrentHitter: null,
          WinningPitcher: 'Cal Quantrill',
          LosingPitcher: 'Eli Morgan',
          SavingPitcher: 'Aroldis Chapman',
          DueUpHitterID1: null,
          DueUpHitterID2: null,
          DueUpHitterID3: null,
          GlobalGameID: 10064540,
          GlobalAwayTeamID: 10000010,
          GlobalHomeTeamID: 10000029,
          PointSpreadAwayTeamMoneyLine: -138,
          PointSpreadHomeTeamMoneyLine: 112,
          LastPlay: null,
          IsClosed: true,
          Updated: '2022-04-23T02:02:31',
          GameEndDateTime: '2022-04-22T22:08:13',
          HomeRotationNumber: 916,
          AwayRotationNumber: 915,
          NeutralVenue: false,
          InningDescription: null,
          OverPayout: -108,
          UnderPayout: -112,
          DateTimeUTC: '2022-04-22T23:05:00',
          SeriesInfo: null,
          Innings: [
            {
              InningID: 416376,
              GameID: 64540,
              InningNumber: 1,
              AwayTeamRuns: 0,
              HomeTeamRuns: 0,
            },
            {
              InningID: 416382,
              GameID: 64540,
              InningNumber: 2,
              AwayTeamRuns: 0,
              HomeTeamRuns: 0,
            },
            {
              InningID: 416386,
              GameID: 64540,
              InningNumber: 3,
              AwayTeamRuns: 0,
              HomeTeamRuns: 2,
            },
            {
              InningID: 416391,
              GameID: 64540,
              InningNumber: 4,
              AwayTeamRuns: 1,
              HomeTeamRuns: 1,
            },
            {
              InningID: 416404,
              GameID: 64540,
              InningNumber: 5,
              AwayTeamRuns: 0,
              HomeTeamRuns: 1,
            },
            {
              InningID: 416417,
              GameID: 64540,
              InningNumber: 6,
              AwayTeamRuns: 0,
              HomeTeamRuns: 0,
            },
            {
              InningID: 416425,
              GameID: 64540,
              InningNumber: 7,
              AwayTeamRuns: 0,
              HomeTeamRuns: 0,
            },
            {
              InningID: 416437,
              GameID: 64540,
              InningNumber: 8,
              AwayTeamRuns: 0,
              HomeTeamRuns: 0,
            },
            {
              InningID: 416448,
              GameID: 64540,
              InningNumber: 9,
              AwayTeamRuns: 0,
              HomeTeamRuns: null,
            },
          ],
        },
        {
          GameID: 64545,
          Season: 2022,
          SeasonType: 1,
          Status: 'Final',
          Day: '2022-04-22T00:00:00',
          DateTime: '2022-04-22T19:05:00',
          AwayTeam: 'MIL',
          HomeTeam: 'PHI',
          AwayTeamID: 32,
          HomeTeamID: 12,
          RescheduledGameID: null,
          StadiumID: 51,
          Channel: 'BSWI,NSPA',
          Inning: 9,
          InningHalf: 'T',
          AwayTeamRuns: 2,
          HomeTeamRuns: 4,
          AwayTeamHits: 5,
          HomeTeamHits: 10,
          AwayTeamErrors: 0,
          HomeTeamErrors: 1,
          WinningPitcherID: 10007095,
          LosingPitcherID: 10009313,
          SavingPitcherID: 10003332,
          Attendance: null,
          AwayTeamProbablePitcherID: 10006935,
          HomeTeamProbablePitcherID: 10008281,
          Outs: null,
          Balls: null,
          Strikes: null,
          CurrentPitcherID: null,
          CurrentHitterID: null,
          AwayTeamStartingPitcherID: 10006935,
          HomeTeamStartingPitcherID: 10008281,
          CurrentPitchingTeamID: null,
          CurrentHittingTeamID: null,
          PointSpread: -1.5,
          OverUnder: 8.0,
          AwayTeamMoneyLine: 105,
          HomeTeamMoneyLine: -124,
          ForecastTempLow: 56,
          ForecastTempHigh: 57,
          ForecastDescription: 'Overcast Clouds',
          ForecastWindChill: 56,
          ForecastWindSpeed: 7,
          ForecastWindDirection: 30,
          RescheduledFromGameID: null,
          RunnerOnFirst: null,
          RunnerOnSecond: null,
          RunnerOnThird: null,
          AwayTeamStartingPitcher: 'Freddy Peralta',
          HomeTeamStartingPitcher: 'Ranger Suárez',
          CurrentPitcher: null,
          CurrentHitter: null,
          WinningPitcher: 'Nick Nelson',
          LosingPitcher: 'Aaron Ashby',
          SavingPitcher: 'Corey Knebel',
          DueUpHitterID1: null,
          DueUpHitterID2: null,
          DueUpHitterID3: null,
          GlobalGameID: 10064545,
          GlobalAwayTeamID: 10000032,
          GlobalHomeTeamID: 10000012,
          PointSpreadAwayTeamMoneyLine: -201,
          PointSpreadHomeTeamMoneyLine: 163,
          LastPlay: null,
          IsClosed: true,
          Updated: '2022-04-22T22:36:27',
          GameEndDateTime: '2022-04-22T22:31:23',
          HomeRotationNumber: 908,
          AwayRotationNumber: 907,
          NeutralVenue: false,
          InningDescription: null,
          OverPayout: -105,
          UnderPayout: -116,
          DateTimeUTC: '2022-04-22T23:05:00',
          SeriesInfo: null,
          Innings: [
            {
              InningID: 416377,
              GameID: 64545,
              InningNumber: 1,
              AwayTeamRuns: 0,
              HomeTeamRuns: 1,
            },
            {
              InningID: 416384,
              GameID: 64545,
              InningNumber: 2,
              AwayTeamRuns: 0,
              HomeTeamRuns: 0,
            },
            {
              InningID: 416390,
              GameID: 64545,
              InningNumber: 3,
              AwayTeamRuns: 1,
              HomeTeamRuns: 0,
            },
            {
              InningID: 416398,
              GameID: 64545,
              InningNumber: 4,
              AwayTeamRuns: 0,
              HomeTeamRuns: 0,
            },
            {
              InningID: 416407,
              GameID: 64545,
              InningNumber: 5,
              AwayTeamRuns: 0,
              HomeTeamRuns: 0,
            },
            {
              InningID: 416418,
              GameID: 64545,
              InningNumber: 6,
              AwayTeamRuns: 0,
              HomeTeamRuns: 0,
            },
            {
              InningID: 416427,
              GameID: 64545,
              InningNumber: 7,
              AwayTeamRuns: 1,
              HomeTeamRuns: 0,
            },
            {
              InningID: 416444,
              GameID: 64545,
              InningNumber: 8,
              AwayTeamRuns: 0,
              HomeTeamRuns: 3,
            },
            {
              InningID: 416462,
              GameID: 64545,
              InningNumber: 9,
              AwayTeamRuns: 0,
              HomeTeamRuns: null,
            },
          ],
        },
      ],
      [
        'Content-Type',
        'application/json',
        'Connection',
        'close',
        'Vary',
        'Accept-Encoding',
        'Vary',
        'Origin',
      ],
    )
